// Generated by gencpp from file weather_pkg/weather.msg
// DO NOT EDIT!


#ifndef WEATHER_PKG_MESSAGE_WEATHER_H
#define WEATHER_PKG_MESSAGE_WEATHER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace weather_pkg
{
template <class ContainerAllocator>
struct weather_
{
  typedef weather_<ContainerAllocator> Type;

  weather_()
    : zipcode()
    , temp(0.0)
    , cloud_cover()
    , pressure(0.0)
    , dew_point(0.0)  {
    }
  weather_(const ContainerAllocator& _alloc)
    : zipcode(_alloc)
    , temp(0.0)
    , cloud_cover(_alloc)
    , pressure(0.0)
    , dew_point(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _zipcode_type;
  _zipcode_type zipcode;

   typedef float _temp_type;
  _temp_type temp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cloud_cover_type;
  _cloud_cover_type cloud_cover;

   typedef float _pressure_type;
  _pressure_type pressure;

   typedef float _dew_point_type;
  _dew_point_type dew_point;




  typedef boost::shared_ptr< ::weather_pkg::weather_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::weather_pkg::weather_<ContainerAllocator> const> ConstPtr;

}; // struct weather_

typedef ::weather_pkg::weather_<std::allocator<void> > weather;

typedef boost::shared_ptr< ::weather_pkg::weather > weatherPtr;
typedef boost::shared_ptr< ::weather_pkg::weather const> weatherConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::weather_pkg::weather_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::weather_pkg::weather_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace weather_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'weather_pkg': ['/home/robotics/git_work/cola-blimp/lab_one_ws/src/weather_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::weather_pkg::weather_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weather_pkg::weather_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather_pkg::weather_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather_pkg::weather_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_pkg::weather_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather_pkg::weather_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::weather_pkg::weather_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dade398ebd0cc7517b4e568c4f3a4764";
  }

  static const char* value(const ::weather_pkg::weather_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdade398ebd0cc751ULL;
  static const uint64_t static_value2 = 0x7b4e568c4f3a4764ULL;
};

template<class ContainerAllocator>
struct DataType< ::weather_pkg::weather_<ContainerAllocator> >
{
  static const char* value()
  {
    return "weather_pkg/weather";
  }

  static const char* value(const ::weather_pkg::weather_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::weather_pkg::weather_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string zipcode\n\
float32 temp\n\
string cloud_cover\n\
float32 pressure\n\
float32 dew_point\n\
";
  }

  static const char* value(const ::weather_pkg::weather_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::weather_pkg::weather_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zipcode);
      stream.next(m.temp);
      stream.next(m.cloud_cover);
      stream.next(m.pressure);
      stream.next(m.dew_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct weather_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::weather_pkg::weather_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::weather_pkg::weather_<ContainerAllocator>& v)
  {
    s << indent << "zipcode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.zipcode);
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
    s << indent << "cloud_cover: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cloud_cover);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    s << indent << "dew_point: ";
    Printer<float>::stream(s, indent + "  ", v.dew_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEATHER_PKG_MESSAGE_WEATHER_H
